FROM alpine:3.21
RUN apk update --no-cache && \
    apk add --no-cache \
    bash \
    git \
    python3 \
    ipython \
    py3-pip \
    py3-ipykernel \
    py3-numpy \
    py3-pandas

CMD ["bash"]
